version: '3.1'
services:
  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: leanote
      MONGO_INITDB_DATABASE: leanote
    volumes:
      - ./mongodb:/data/db
      - ./leanote/mongodb_backup/leanote_install_data:/leanote_install_data
      - ./dbinit.sh:/docker-entrypoint-initdb.d/dbinit.sh
      - ./leanote.js:/leanote.js
  leanote:
    depends_on:
     - mongo
    links:
     - mongo:mongodb
    image: zxfishhack/leanote
    restart: always
    volumes:
      - ./datas/files:/leanote/src/github.com/leanote/leanote/files
      - ./datas/upload:/leanote/src/github.com/leanote/leanote/public/upload
      - ./app.conf:/leanote/src/github.com/leanote/leanote/conf/app.conf
    ports:
      - 9001:9000 
